# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'demoSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoSwift

    pod 'Just', '~> 0.5.7'
    pod 'Kingfisher', '~> 3.2.4'

  target 'demoSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
